[package]
name = "rottenbrit"
version = "0.1.0"
authors = ["J. Cliff Dyer <jcd@sdf.org>"]

[dependencies]
clap = "2"
mio = "0.6"
slab = "0.4"
serde = "1"
serde_derive = "1"
serde_bencode = "0.2"
serde_bytes = "0.10"

# examples/connect.rs
reqwest = "*"
url = "1.6"
